// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJhl7hf_DD6spyVopzniR1O_6g8uw_1Zg',
    appId: '1:88070435641:web:013e908f8263ca2886eee8',
    messagingSenderId: '88070435641',
    projectId: 'fkdatahub1',
    authDomain: 'fkdatahub1.firebaseapp.com',
    storageBucket: 'fkdatahub1.firebasestorage.app',
    measurementId: 'G-QYECKHPHY5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA87yRQXG4ix4NcRggjNYdS5Iej2yWR6-8',
    appId: '1:88070435641:android:8b8424c844386e5d86eee8',
    messagingSenderId: '88070435641',
    projectId: 'fkdatahub1',
    storageBucket: 'fkdatahub1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCZvpN2BKz_dpjIiO6APs5zBlqwT6WTpA',
    appId: '1:88070435641:ios:6b41cbe355b2c97c86eee8',
    messagingSenderId: '88070435641',
    projectId: 'fkdatahub1',
    storageBucket: 'fkdatahub1.firebasestorage.app',
    iosBundleId: 'com.example.fkdatahub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCZvpN2BKz_dpjIiO6APs5zBlqwT6WTpA',
    appId: '1:88070435641:ios:6b41cbe355b2c97c86eee8',
    messagingSenderId: '88070435641',
    projectId: 'fkdatahub1',
    storageBucket: 'fkdatahub1.firebasestorage.app',
    iosBundleId: 'com.example.fkdatahub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJhl7hf_DD6spyVopzniR1O_6g8uw_1Zg',
    appId: '1:88070435641:web:a9585c00e6680d3a86eee8',
    messagingSenderId: '88070435641',
    projectId: 'fkdatahub1',
    authDomain: 'fkdatahub1.firebaseapp.com',
    storageBucket: 'fkdatahub1.firebasestorage.app',
    measurementId: 'G-RNEEMJ07PQ',
  );
}
